name: Create PR for bump version
on:
  push:
    # branches:
    #   - devel
jobs:
  update-version-pr:
    name: Install dependancies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
            apt-get update && apt-get install -y build-essential pkg-config libssl-dev jq git
            cargo install cargo-bump
            cargo bump minor
            echo "PROJECT_VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Cargo.toml v${{ env.PROJECT_VERSION }}
          branch: create-pull-request/release
          base: devel
          delete-branch: true
          title: Update Cargo.toml v${{ env.PROJECT_VERSION }}
          body: |
            Update cargo version
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: release
          assignees: |
            saorio

